---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-solutions-images/concourse-helm-gcp
    tag: v0.2.0

inputs:
- name: app-source

run:
  path: bash
  args:
  - -exc
  - |
    cd app-source && git tag -l --points-at HEAD | tail -n1 > version
    